using UnityEngine;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;

public static class SaveSystem
{
    private static string GetSavePath(string key)
    {
        // Save files as individual secure binary files in persistent data path
        return Path.Combine(Application.persistentDataPath, key + ".dat");
    }

    /// <summary>
    /// Saves any serializable object to a secure binary file.
    /// </summary>
    public static void Save<T>(string key, T data)
    {
        string path = GetSavePath(key);
        try
        {
            BinaryFormatter formatter = new BinaryFormatter();
            using (FileStream stream = new FileStream(path, FileMode.Create))
            {
                formatter.Serialize(stream, data);
            }
            Debug.Log($"Successfully saved data to {path}");
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Failed to save data to {path}: {e.Message}");
        }
    }

    /// <summary>
    /// Loads a serializable object from a secure binary file.
    /// </summary>
    public static T Load<T>(string key)
    {
        string path = GetSavePath(key);
        if (!File.Exists(path))
        {
            return default(T);
        }

        try
        {
            BinaryFormatter formatter = new BinaryFormatter();
            using (FileStream stream = new FileStream(path, FileMode.Open))
            {
                return (T)formatter.Deserialize(stream);
            }
        }
        catch (System.Exception e)
        {
            Debug.LogError($"Failed to load data from {path}: {e.Message}");
            return default(T);
        }
    }

    /// <summary>
    /// Checks if a save file exists for a given key.
    /// </summary>
    public static bool Exists(string key)
    {
        return File.Exists(GetSavePath(key));
    }

    /// <summary>
    /// Deletes a save file for a given key.
    /// </summary>
    public static void Delete(string key)
    {
        string path = GetSavePath(key);
        if (File.Exists(path))
        {
            File.Delete(path);
            Debug.Log($"Deleted save data at {path}");
        }
    }

    /// <summary>
    /// Deletes all saved files generated by this SaveSystem and wipes PlayerPrefs.
    /// </summary>
    public static void ClearAll()
    {
        string directory = Application.persistentDataPath;
        if (Directory.Exists(directory))
        {
            string[] files = Directory.GetFiles(directory, "*.dat");
            foreach (string file in files)
            {
                try
                {
                    File.Delete(file);
                }
                catch (System.Exception e)
                {
                    Debug.LogWarning($"Failed to delete file {file}: {e.Message}");
                }
            }
        }

        PlayerPrefs.DeleteAll();
        PlayerPrefs.Save();
        Debug.Log("Cleared all save data (Binary files & PlayerPrefs).");
    }
}

/// <summary>
/// Serializable wrapper for UnityEngine.Vector3 to allow binary formatting.
/// </summary>
[System.Serializable]
public struct SerializableVector3
{
    public float x;
    public float y;
    public float z;

    public SerializableVector3(Vector3 v)
    {
        x = v.x;
        y = v.y;
        z = v.z;
    }

    public Vector3 ToVector3()
    {
        return new Vector3(x, y, z);
    }

    public static implicit operator SerializableVector3(Vector3 v) => new SerializableVector3(v);
    public static implicit operator Vector3(SerializableVector3 sv) => sv.ToVector3();
}

/// <summary>
/// Serializable wrapper for UnityEngine.Quaternion to allow binary formatting.
/// </summary>
[System.Serializable]
public struct SerializableQuaternion
{
    public float x;
    public float y;
    public float z;
    public float w;

    public SerializableQuaternion(Quaternion q)
    {
        x = q.x;
        y = q.y;
        z = q.z;
        w = q.w;
    }

    public Quaternion ToQuaternion()
    {
        return new Quaternion(x, y, z, w);
    }

    public static implicit operator SerializableQuaternion(Quaternion q) => new SerializableQuaternion(q);
    public static implicit operator Quaternion(SerializableQuaternion sq) => sq.ToQuaternion();
}
