// <auto-generated>
// Per-asset material parameters for the 64 Meshy imports under
// "Assets/3D Assets/Jannah Garden Assets".
//
// Derived by sampling each asset's source maps:
//   hasEmission     - emission map contains anything above near-black
//   specBrightness  - 0.5 + mean(metallic), clamped to [0.5, 1.5]
//   specSmoothness  - 60 + 180 * mean(metallic), clamped to [40, 250]
//   specColor       - white for dielectrics, tinted toward the mean albedo
//                     as mean(metallic) rises
//
// Regenerate rather than hand-edit. Consumed by JannahGardenMaterialGenerator.
// </auto-generated>

using UnityEngine;

public static class JannahGardenAssetTable
{
    public readonly struct Entry
    {
        public readonly string Folder;          // asset folder name (a UUID)
        public readonly string MaterialName;    // human-readable, unique
        public readonly string AlbedoFile;      // base colour map file name
        public readonly bool   HasEmission;     // emission map is not all black
        public readonly float  SpecBrightness;
        public readonly float  SpecSmoothness;
        public readonly Color  SpecColor;

        public Entry(string folder, string materialName, string albedoFile, bool hasEmission,
                     float specBrightness, float specSmoothness, Color specColor)
        {
            Folder = folder;
            MaterialName = materialName;
            AlbedoFile = albedoFile;
            HasEmission = hasEmission;
            SpecBrightness = specBrightness;
            SpecSmoothness = specSmoothness;
            SpecColor = specColor;
        }
    }

    public static readonly Entry[] Entries =
    {
        new Entry("019fd744-4bb4-7ff0-b1b0-7690092c0126", "Ancient_Stone_Fountai", "Meshy_AI_Ancient_Stone_Fountai_0806145350_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd749-e140-7155-8e56-fabf63718ee1", "Ancient_Stone_Pool", "Meshy_AI_Ancient_Stone_Pool_0806145350_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd75b-2808-7467-8085-10b81c90a994", "Arabic_Calligraphy_St", "Meshy_AI_Arabic_Calligraphy_St_0806141334_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74c-3d9b-71a3-b3f3-2bf34d956ec8", "Arabic_Script_Archway", "Meshy_AI_Arabic_Script_Archway_0806141743_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74f-aa4e-713a-82a8-74c3bc0eec60", "Arched_Timber_Bridge", "Meshy_AI_Arched_Timber_Bridge_0806141743_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd754-0629-71de-a125-f877e6542a40", "Azure_Mosaic_Bench", "Meshy_AI_Azure_Mosaic_Bench_0806141451_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd750-afcf-7285-a4d1-f6c608e037ea", "Bismillah_Portal_Ring", "Meshy_AI_Bismillah_Portal_Ring_0806141548_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd743-ef2c-7fd5-a669-b9334202d205", "Blue_Mosaic_Octagonal", "Meshy_AI_Blue_Mosaic_Octagonal_0806145523_texture.png", true, 0.586f, 75.4f, new Color(0.9683f, 0.9936f, 1.0f, 1f)),
        new Entry("019fd74b-fc35-7190-8fa3-3d172ab2bad5", "Blue_Star_Mosaic_Slab", "Meshy_AI_Blue_Star_Mosaic_Slab_0806141743_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74b-cab9-717f-a7b7-809a21aeb81a", "Celestial_Blossom_Tre", "Meshy_AI_Celestial_Blossom_Tre_0806141743_texture.png", true, 0.502f, 60.4f, new Color(0.9994f, 0.9995f, 1.0f, 1f)),
        new Entry("019fd752-9dea-71ac-983c-25a48ddc5d03", "Corinthian_Column", "Meshy_AI_Corinthian_Column_0806141451_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd75b-9103-73e5-8b56-61c73bdee108", "Crimson_Diamond_on_a_", "Meshy_AI_Crimson_Diamond_on_a__0806141335_texture.png", true, 1.064f, 161.5f, new Color(1.0f, 0.6699f, 0.6774f, 1f)),
        new Entry("019fd755-2101-7327-85f8-093ed25da565", "Crystal_Citadel", "Meshy_AI_Crystal_Citadel_0806141452_texture.png", true, 0.875f, 127.6f, new Color(0.9336f, 0.9463f, 1.0f, 1f)),
        new Entry("019fd750-27df-7248-aba6-4d2d897609fe", "Eight_Point_Star_Mosa", "Meshy_AI_Eight_Point_Star_Mosa_0806141743_texture.png", true, 0.502f, 60.4f, new Color(0.9998f, 1.0f, 0.9999f, 1f)),
        new Entry("019fd755-497b-7200-b2fb-c1a9f43bc1a7", "Eight_Pointed_Star_La", "Meshy_AI_Eight_Pointed_Star_La_0806141451_texture.png", true, 1.016f, 152.9f, new Color(1.0f, 0.916f, 0.7275f, 1f)),
        new Entry("019fd751-7507-720f-85f8-e780338df37b", "Emerald_Velvet_Cushio", "Meshy_AI_Emerald_Velvet_Cushio_0806141548_texture.png", false, 0.548f, 68.6f, new Color(0.9901f, 1.0f, 0.9747f, 1f)),
        new Entry("019fd75b-cbd0-73f1-824c-cdf9640f52dd", "Floating_Lotus_Altar", "Meshy_AI_Floating_Lotus_Altar_0806141335_texture.png", true, 0.713f, 98.3f, new Color(1.0f, 0.9578f, 0.9354f, 1f)),
        new Entry("019fd75c-1e1b-74e2-8a88-d59f2daaa530", "Floating_Meadow", "Meshy_AI_Floating_Meadow_0806141335_texture.png", false, 0.5f, 60.1f, new Color(0.9999f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd752-448c-7299-9aa7-c7d261a155d0", "Floating_Stone_Path", "Meshy_AI_Floating_Stone_Path_0806141548_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd75a-6e2d-734c-95b1-73c0c5a1e96c", "Golden_Archway_of_Lig", "Meshy_AI_Golden_Archway_of_Lig_0806141335_texture.png", true, 0.602f, 78.3f, new Color(1.0f, 0.9789f, 0.9521f, 1f)),
        new Entry("019fd755-a65c-721b-8406-8b1a4b5239fe", "Golden_Crescent_Star_", "Meshy_AI_Golden_Crescent_Star__0806141452_texture.png", true, 1.136f, 174.5f, new Color(1.0f, 0.8661f, 0.6155f, 1f)),
        new Entry("019fd750-e0ff-71e7-9465-52e242f85963", "Golden_Fountain_of_Li", "Meshy_AI_Golden_Fountain_of_Li_0806141548_texture.png", true, 0.502f, 60.4f, new Color(1.0f, 0.9998f, 0.9991f, 1f)),
        new Entry("019fd754-37bc-71e2-85b4-ce7a16526388", "Golden_Gateway_to_Par", "Meshy_AI_Golden_Gateway_to_Par_0806141452_texture.png", true, 1.388f, 219.9f, new Color(1.0f, 0.7547f, 0.3068f, 1f)),
        new Entry("019fd75a-9879-73a7-bcfc-cf491522314f", "Golden_Quranic_Panel", "Meshy_AI_Golden_Quranic_Panel_0806141334_texture.png", true, 1.084f, 165.2f, new Color(1.0f, 0.86f, 0.7243f, 1f)),
        new Entry("019fd754-8dfa-728f-b272-559d8c3f4a17", "Iridescent_Trail", "Meshy_AI_Iridescent_Trail_0806141452_texture.png", true, 1.04f, 157.3f, new Color(0.7724f, 0.8247f, 1.0f, 1f)),
        new Entry("019fd740-fb00-7f45-8883-6277e7b83fe7", "Isle_of_Spring", "Meshy_AI_Isle_of_Spring_0806145639_texture.png", true, 0.5f, 60.1f, new Color(0.9999f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd752-18df-7230-9073-3541023b0cfa", "Ivy_Clad_Cottage", "Meshy_AI_Ivy_Clad_Cottage_0806141548_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd75b-f6e8-73c0-9fb2-3b835b73a8c3", "Lantern_Ascension", "Meshy_AI_Lantern_Ascension_0806141334_texture.png", true, 0.647f, 86.5f, new Color(1.0f, 0.9699f, 0.9283f, 1f)),
        new Entry("019fd74a-60cd-7060-8a23-e30b39b79f33", "Lotus_Pond", "Meshy_AI_Lotus_Pond_0806145350_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd743-a857-7fc5-a17e-8cf68524ae1f", "Low_Poly_Coconut_Palm", "Meshy_AI_Low_Poly_Coconut_Palm_0806145522_texture.png", false, 0.5f, 60.1f, new Color(0.9999f, 1.0f, 0.9997f, 1f)),
        new Entry("019fd742-0aae-7046-87c9-1b52e8d937e6", "Luminal_Rift", "Meshy_AI_Luminal_Rift_0806145522_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74b-9334-70ef-aab0-c92929f3bfde", "Luminous_Weeping_Will", "Meshy_AI_Luminous_Weeping_Will_0806145351_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd74a-864e-713e-a0da-054ccba49f8f", "Marble_Water_Channel_", "Meshy_AI_Marble_Water_Channel__0806145350_texture.png", false, 0.517f, 63.0f, new Color(0.9998f, 1.0f, 1.0f, 1f)),
        new Entry("019fd742-7d6c-7fa3-82fd-dddac95b30a1", "Meandering_River_Isla", "Meshy_AI_Meandering_River_Isla_0806145522_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 0.9999f, 1f)),
        new Entry("019fd742-a4b7-7fce-81a4-8b5fda8dcd11", "Moonlit_Cactus_Bloom", "Meshy_AI_Moonlit_Cactus_Bloom_0806145523_texture.png", true, 0.501f, 60.2f, new Color(0.9999f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd750-600a-715b-81ec-f8fc40a60e38", "Moonlit_Ring_in_a_Sto", "Meshy_AI_Moonlit_Ring_in_a_Sto_0806141743_texture.png", true, 0.5f, 60.0f, new Color(0.9999f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74f-e0b9-722e-954c-2463277b4b8a", "Muqarnas_Arch_with_Ca", "Meshy_AI_Muqarnas_Arch_with_Ca_0806141743_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd751-ab9d-7182-9357-4d53dc2ff68b", "Ornate_Bonsai_in_a_Ca", "Meshy_AI_Ornate_Bonsai_in_a_Ca_0806141548_texture.png", false, 0.501f, 60.2f, new Color(1.0f, 1.0f, 0.9997f, 1f)),
        new Entry("019fd755-d532-7223-92e7-dbad92e34f13", "Ornate_Golden_Censer", "Meshy_AI_Ornate_Golden_Censer_0806141334_texture.png", true, 1.115f, 170.8f, new Color(1.0f, 0.8945f, 0.696f, 1f)),
        new Entry("019fd75b-5c4b-73d8-b942-4956b951d703", "Ornate_Golden_Goblet", "Meshy_AI_Ornate_Golden_Goblet_0806141335_texture.png", false, 1.256f, 196.0f, new Color(1.0f, 0.8596f, 0.6983f, 1f)),
        new Entry("019fd75a-df94-7474-929e-e37928161495", "Ornate_Lantern_Galler", "Meshy_AI_Ornate_Lantern_Galler_0806141334_texture.png", true, 0.856f, 124.0f, new Color(1.0f, 0.9042f, 0.8102f, 1f)),
        new Entry("019fd751-1240-716c-b8bc-558ad26335b8", "Ornate_Medallion_Rug_", "Meshy_AI_Ornate_Medallion_Rug__0806141548_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 0.9999f, 1f)),
        new Entry("019fd740-bc3f-7f84-b973-0441da9fb98c", "Petal_Cascade", "Meshy_AI_Petal_Cascade_0806145639_texture.png", true, 0.502f, 60.3f, new Color(1.0f, 0.9997f, 0.9997f, 1f)),
        new Entry("019fd748-592c-70bc-bbd8-afc1405d16df", "Pineapple_Crown_Fount", "Meshy_AI_Pineapple_Crown_Fount_0806145350_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74b-4b66-7198-87df-f86877fcc113", "Pink_Rose_Garden_in_a", "Meshy_AI_Pink_Rose_Garden_in_a_0806145350_texture.png", false, 0.5f, 60.1f, new Color(1.0f, 1.0f, 0.9999f, 1f)),
        new Entry("019fd74a-e240-70df-a77e-f5c12d24f9ef", "Pomegranate_Tree_0806145350", "Meshy_AI_Pomegranate_Tree_0806145350_texture.png", false, 0.501f, 60.1f, new Color(1.0f, 1.0f, 0.9996f, 1f)),
        new Entry("019fd741-4df5-7f58-979d-34c4f23ef887", "Pomegranate_Tree_0806145639", "Meshy_AI_Pomegranate_Tree_0806145639_texture.png", false, 0.501f, 60.1f, new Color(0.9999f, 1.0f, 0.9996f, 1f)),
        new Entry("019fd74a-2cd7-70c7-b6a1-1ae3e4cd06dc", "Prismatic_Bloom", "Meshy_AI_Prismatic_Bloom_0806145350_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd751-df5f-7283-a69d-21ce0b39341f", "Prismatic_Cascade", "Meshy_AI_Prismatic_Cascade_0806141548_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74f-0822-7127-882f-0a86b12e50db", "River_of_Gold", "Meshy_AI_River_of_Gold_0806141743_texture.png", true, 0.5f, 60.1f, new Color(1.0f, 0.9999f, 0.9997f, 1f)),
        new Entry("019fd752-cb5c-71b2-9d5b-f10b344739ec", "Ropebound_Bamboo_Arch", "Meshy_AI_Ropebound_Bamboo_Arch_0806141451_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd750-8a50-71df-9dd6-ef95167026a5", "Ruby_Gold_Arched_Gate", "Meshy_AI_Ruby_Gold_Arched_Gate_0806141743_texture.png", true, 1.195f, 185.2f, new Color(1.0f, 0.7791f, 0.5265f, 1f)),
        new Entry("019fd755-7ddd-733b-bae0-c91e472c4657", "Runic_Fire_Ring", "Meshy_AI_Runic_Fire_Ring_0806141452_texture.png", true, 0.923f, 136.2f, new Color(1.0f, 0.9577f, 0.9043f, 1f)),
        new Entry("019fd754-f7ac-7315-8fa2-521e6487e994", "Star_Lantern", "Meshy_AI_Star_Lantern_0806141452_texture.png", true, 1.079f, 164.2f, new Color(1.0f, 0.8557f, 0.7236f, 1f)),
        new Entry("019fd741-7de3-7f6b-abe9-62c5ddd38ca5", "Starflower_Trellis", "Meshy_AI_Starflower_Trellis_0806145639_texture.png", true, 0.502f, 60.3f, new Color(1.0f, 1.0f, 0.9996f, 1f)),
        new Entry("019fd751-3e70-71fc-9ae6-0115408b6d33", "Tiered_Cascade", "Meshy_AI_Tiered_Cascade_0806141548_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd743-0af6-7fb8-8c9a-e132bcf8cef6", "Tree_of_Light", "Meshy_AI_Tree_of_Light_0806145523_texture.png", true, 0.509f, 61.7f, new Color(0.9995f, 0.999f, 1.0f, 1f)),
        new Entry("019fd741-bc42-7f9c-a542-23cd902d6799", "Tulip_Cluster", "Meshy_AI_Tulip_Cluster_0806145522_texture.png", false, 0.5f, 60.1f, new Color(0.9999f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd74f-706b-71ae-80a1-0dbf244f2162", "Turquoise_Mosaic_Arch", "Meshy_AI_Turquoise_Mosaic_Arch_0806141743_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd752-7040-72a1-b415-d57b2058a277", "Vine_Wrapped_Bamboo_A", "Meshy_AI_Vine_Wrapped_Bamboo_A_0806141548_texture.png", false, 0.501f, 60.1f, new Color(1.0f, 0.9998f, 0.9996f, 1f)),
        new Entry("019fd743-764e-7ede-b743-9668b0e6c7ab", "Whimsical_Apple_Tree", "Meshy_AI_Whimsical_Apple_Tree_0806145522_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd74b-1aa0-70e2-9086-1618e73d50a0", "Whimsical_Floral_Casc", "Meshy_AI_Whimsical_Floral_Casc_0806145351_texture.png", true, 0.5f, 60.1f, new Color(0.9999f, 1.0f, 0.9998f, 1f)),
        new Entry("019fd742-cd08-7ec7-87c0-dc90890109ac", "Whispering_Blossom_Tr", "Meshy_AI_Whispering_Blossom_Tr_0806145523_texture.png", true, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
        new Entry("019fd742-4b48-7eb0-aea6-9601826b4185", "Whispering_Well", "Meshy_AI_Whispering_Well_0806145522_texture.png", false, 0.5f, 60.0f, new Color(1.0f, 1.0f, 1.0f, 1f)),
    };
}
